### ISSUE TITLE
Problem: Not able to delete accumulated avatar and header images

### ISSUE THREAD

**Issue by jorgesat** [magicstone-dev/ecko#446]
The tootctl cron job currently deletes attached media after certain period of time. However, many admins are complaining that there is a large amount of disk space being used in avatar and header images, especially from large instances and from old instances and accounts that no longer exist.

Please see: https://github.com/mastodon/mastodon/issues/9567

*Proposed solution:* Enabling the possibility to delete such images from disk.

**Comment by weex** [comment]
Looks like a valid problem to me. There seem to be several solutions offered in that thread and one that was merged 8 days ago on setting a retention policy. Not sure which would be best but we'll merge it when a pull request is created!

**Comment by weex** [comment]
Seems to be a possible solution. https://github.com/mastodon/mastodon/pull/18397

**Comment by weex** [comment]
The above PR gave modest results.
```
2219/2219 |=======================================| Time: 00:23:34
OK, pruned 2196 accounts
```

Before (from `tootctl media usage`):
```
Avatars:	5.65 GB (3.05 MB local)
Headers:	12.2 GB (2.04 MB local)
```
After
```
Avatars:	5.5 GB (3.05 MB local)
Headers:	11.9 GB (2.04 MB local)
```

**Comment by evanphilip** [comment]
Is this issue resolved by https://github.com/mastodon/mastodon/pull/22149, which closed issue https://github.com/mastodon/mastodon/issues/9567?

**Comment by weex** [comment]
@evanphilip 

> Is this issue resolved by [mastodon/mastodon#22149](https://github.com/mastodon/mastodon/pull/22149), which closed issue [mastodon/mastodon#9567](https://github.com/mastodon/mastodon/issues/9567)?

Great work! It's not resolved yet, but if you want to submit as a PR (and it passes our very similar CI) we'll merge it.
